name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk21-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan Tests
        run: ./gradlew test --scan | tee scan.log

      - name: Build
        run: ./gradlew bootJar | tee build.log

      - name: Collect output artifacts
        run: |
          echo "# Build output" >> $GITHUB_STEP_SUMMARY
          echo "$(cat build.log | tail -n 2)" >> $GITHUB_STEP_SUMMARY
          echo "# Test results" >> $GITHUB_STEP_SUMMARY
          echo "$(cat scan.log | tail -n 2)" >> $GITHUB_STEP_SUMMARY

  sonar-static-analysis:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk21-alpine
    needs: ci
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Analysis
        run: ./gradlew sonar -Dsonar.gradle.skipCompile=true
