name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk21-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./gradle bootJar

  analysis:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk21-alpine
    env:
      - SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Analysis
        run: ./gradlew sonar -Dsonar.gradle.skipCompile=true
